apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocart
  labels:
    app: gocart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gocart
  template:
    metadata:
      labels:
        app: gocart
    spec:
      containers:
      - name: gocart
        image: mohdjishin/goocart
        ports:
        - containerPort: 3000
        resources:   # set resource limits
          requests: # set resource requests minimum
            cpu: 100m
            memory: 128Mi
        
          limits:   # set resource limits maximum
            cpu: 500m
            memory: 512Mi
