version: '3'

services:

  web:
    build: .
    container_name: web
    restart: on-failure
    ports:
      - 8080:3000

    environment:
      - PORT=${PORT}
      - OOOO=database

      - DNS=host=database user=postgres password=password port=5432 dbname=gocart  sslmode=disable


      - SECRET=${SECRET}


      - TWILIO_AUTH_TOKEN =${TWILIO_AUTH_TOKEN}
      - VERIFY_SERVICE_SID=${VERIFY_SERVICE_SID}



      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}


      - PAYMENT_SEC_KEY=${PAYMENT_SEC_KEY}
  database:
    image: postgres:latest
    # container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: gocart
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - p-data:/var/lib/postgresql/data
volumes:
  p-data:
    driver: local
